### ISSUE TITLE
Function not found `setdecimal_to_r`

### ISSUE THREAD

**Issue by sarahromanes** [lebebr01/SPSStoR#3]
Hey!
Just tried to use this with a file that has the first line of
`SET decimal dot.`

When I try and use the `spss_to_r` function I get the following issue:

```
Error in setdecimal_to_r("SET decimal dot.", TRUE, FALSE) : 
  could not find function "setdecimal_to_r"
```

Is there a function that has not been uploaded?
Best,
Sarah

FYI - this is the SPSS file https://www.oecd.org/pisa/pisaproducts/PISA2012_SPSS_student.txt

**Comment by sarahromanes** [comment]
Related:
```
Error in datalist_to_r(c("DATA LIST FILE \"C:\\XXX\\INT_STU12_DEC03.txt\" /",  : 
  could not find function "datalist_to_r"
```

**Comment by lebebr01** [comment]
Thanks for your interest in the package. Unfortunately, these functions have not been created for the package and currently I'm not actively adding additional functionality to the package, although this may change in the future. I'm currently focusing my limited development time on other packages.

In looking briefly at the top of your SPSS syntax file, this appears to be trying to read in a fixed width data file. Currently the package supports reading in text files, excel files, or SPSS data files. 

With all that said, I do see the usefulness of adding fixed width files as many publicly available national data sets are formatted this way, including some that I use as well. As such, I'm going to leave this issue open and may attempt to tackle this soonish.

Finally, I'm open/encourage PRs if you or others are interested in adding this functionality.

**Comment by shevonlicorish** [comment]
@lebebr01 has this package been totally removed/disabled? I cannot get it to install in R. Please advise.

**Comment by lebebr01** [comment]
Thanks for the message. The package is not on CRAN, and largely has not been supported for multiple years. Therefore, the conversion process may not generate proper/valid R code any longer due to changes in the R packages.

I did confirm it does still install on my mac with the following command: 

```r
remotes::install_github("lebebr01/SPSStoR")
```
